services:
  core_app:
    build:
      context: .
      dockerfile: Dockerfile.core_app

    restart: always

    volumes:
      - my_data:/app/data

    env_file:
      - ".env"

    image: tg_core_app:1.0.0

volumes:
  my_data:
