[project]
name = "note-taking-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "faker>=36.1.1",
    "pillow>=11.1.0",
    "python-dotenv>=1.0.1",
    "python-telegram-bot>=21.11.1",
    "sqlmodel>=0.0.23",
]
